# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago'}, { name: 'Copenhagen'}])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#Announcements
Announcement.create(posted_by: '1', title: 'Farewell Party for Mr Ameir Hussan', content: 'Unfortunately for us, I have to inform you that Mr. Hussan will be leaving GoFast as of September 30th.  Mr. Hussan has been with the company for 25 years and will be retiring at age of 63.  Mr. Hussan has been a role model to many drivers, a perfect driving record with no accidents on the road for over 30 years.  Very few people can claim such a great achievement!  Mr. Hussan has always been a good friend and a great co-worker.  His driving techniques will be passed on to many generations of drivers to come and he will be sorely missed in GoFast.  As such, we are throwing a Farewell party for Mr. Ameir Hussan on Saturday September 21st at 05:00 pm at the office.  Please join us for free drinks and food as we celebrate Mr. Hussans successful carreer as a professional long haul truck driver!  See you then!', date_posted: '2013-09-16')
Announcement.create(posted_by: '2', title: 'Welcome Mr Breown!', content: 'It is my great pleasure to introduce to your our newest addition to the list of our amazing drivers, Mr. Michael Breown!  Mr Breown has been a driver for nearly 17 years now and is excited to join our company.  He will be taking over truck 1007 and trialer 2007 in place of Mr Ameir Hussan, who you all know will be retiring at the end of the month.  Mr Breown has demonstrated safe driving techiniques and has proven his commitment to delivering customer goods in compliance with all applicable MTO/DOT regulations.  Having said this please help me wish Mr. Breown to our company as our newest driver!  Welcome to GoFast Mr. Michael Brown!', date_posted: '2013-09-16')
Announcement.create(posted_by: '3', title: 'Office Renovation', content: 'From September 15th to December 21st we will be doing renovations in the office.  We would like to ask each employee to be careful when coming in the officer.  There will be safety signs posted where applicable so when coming to the office please pay close attention to the signs to prevent self injury.  We were assured by the renovation agency that they will do everything in their power to protect the visitors to the officer as well as the workers in the office so please follow their instructions should they give you any when entering the premises.  If you have any problems with the work above, or you have any questions feel free to contact the office during our work hours.  Thank you all for your patience and understand, we hope these changes will greatly improve the working environment within the office.', date_posted: '2013-09-07')
Announcement.create(posted_by: '1', title: 'Thanksgiving!', content: 'Happy Thanksgiving!  In spirits of thanks giving we would like to thank you all for your hard efforts in making this company the best it can be.  We understand the difficulties of each of your jobs and we wanted to thank you all by giving you all a restaurant giftcard.  The giftcards are located in the office and please speak to Marry about getting yours.  She will be in the office all weeek so drop by when you can and pick up your gift card!  Once again, thank you all for your hard work and Happy  Thanksgiving!', date_posted: '2013-10-01')
Announcement.create(posted_by: '2', title: 'Halloween!', content: 'To all employees we wish you a happy halloween!  In the spirit of halloween we will be giving away candy packages to each employee at the office.  Each employee is qualified to receive 1 candy package per child they are a parrent of.  Packages are available as of November October 31st until November 8th.  You may drop by anytime, just ensure to sign the page that you have receieved your packages!  Once again, we wish you happy halloween!', date_posted: '2013-10-21')
Announcement.create(posted_by: '3', title: 'New Driver Job Opening', content: 'We are hiring a new long haul driver to start as of December 15th 2013.  We offer competitive wages and have a schedule that we follow as much as possible.  Before applying please ensure that you meet our standards.  In brief, we expect our drivers to safely operate trucks and trailers while moving freight and containers for our customers.  We expect drivers to posses and maintain a safe driving record and are expected to conduct our service in compliance with all applicable MTO/DOT regulations.  We also expect our drivers to be courteous, polite and professional at all times.  In order to join the team you must be over age of 20, you must have 1-year verifiable North American commercial vehicle driving experience.  You must have valid Class AZ licence and Professional attitude.  Those interested in applying please see more details listed under Job Postings.  Best of luck and we hope to hear from you.', date_posted: '2013-10-30')
Announcement.create(posted_by: '1', title: 'New Truck', content: 'I am pleased to confirm that we are receiving a brand new truck, model 2013 which will be in service as of December 15th!  With the addition of the new truck, we will be hiring a new driver who will become part of our team in delivering goods to our customers with great care and accuracy.  The truck is a Volvo VNL 780 imported all the way from United Kingdom!  The VNL in many ways is the ultimate truck, it is meant for long hauls and team drivers.  It has 500 hp and is 1850 lb heavy.  It has AutoShift and Ultrashift with 12 speeds.', date_posted: '2013-11-16')
Announcement.create(posted_by: '2', title: 'New Trailers!', content: 'Great News!  Over the past couple of months we have been receiving a lot of complaints regarding the trailers 2001, 2002, and 2003.  While we have been fully understanding the faults with the trailers, we unfortunately were not in a position to afford new trailers at that time.  Due to recent increase in business, I am pleased to announce that we will be receiveing new trailers within 2 weeks from today.  These trailers have been purchased and now are being prepared with minor justifications that we have requestd to better suit our busines needs.  These three new trailers that we have ordered will be replacing trailer numbers: 2001, 2002, and 2003.', date_posted: '2013-11-30')

#Companies
Company.create(company_type: 'driver', name: 'Hussan Express', street: '2372 Eglinton Ave W', unit: '', city: 'Mississuaga', province: 'Ontario', postal_code: 'M9B 2B2', email: 'hussan_express@gmail.com', primary_phone: '4168638475', secondary_phone: '', fax: '', contact_name: 'Ameir Hussan')
Company.create(company_type: 'driver', name: 'Majid Trucking', street: '2605 Innisfil Road', unit: '', city: 'Mississuaga', province: 'Ontario', postal_code: 'M9B 3R4', email: 'majid_trucking@gmail.com', primary_phone: '4162600471', secondary_phone: '', fax: '', contact_name: 'Arshad Majid')
Company.create(company_type: 'driver', name: 'Prosyk Transportation', street: '3094 Splendour Place', unit: '', city: 'Mississuaga', province: 'Ontario', postal_code: 'M9B 2G9', email: 'prosyk_transportation@gmail.com', primary_phone: '4167807559', secondary_phone: '', fax: '', contact_name: 'Jason	Prosyk')
Company.create(company_type: 'driver', name: 'Myhal Express', street: '6691 Harlow Road', unit: '', city: 'Mississuaga', province: 'Ontario', postal_code: 'M9B 6G1', email: 'myhal_express@gmail.com', primary_phone: '4168986281', secondary_phone: '', fax: '', contact_name: 'Peter	Myhal')
Company.create(company_type: 'customer', name: 'Zellers Incorporated', street: '153 West 20th Avenue', unit: '20', city: 'Vancouver', province: 'British Columbia', postal_code: 'L5D 3R3', email: 'shipping@zellers.com', primary_phone: '6044239484', secondary_phone: '', fax: '', contact_name: 'John MacDonald')
Company.create(company_type: 'customer', name: 'Cannon Goods', street: '7642 Cavendish Drive', unit: '19', city: 'Niagara Falls', province: 'Ontario', postal_code: 'G4Z 5T4', email: 'shipping@cannon-goods.com', primary_phone: '4764345494', secondary_phone: '', fax: '', contact_name: 'Ben Hilton')
Company.create(company_type: 'customer', name: 'JYSK', street: '28 Wood Street', unit: '14', city: 'Toronto', province: 'Ontario', postal_code: 'L8K 9C3', email: 'shipping@JYSK.com', primary_phone: '4162763358', secondary_phone: '', fax: '', contact_name: 'Jean Raynold')
Company.create(company_type: 'customer', name: 'Wallmart', street: '1017 Bay Street', unit: '12', city: 'Toronto', province: 'Ontario', postal_code: 'L8K 8C3', email: 'repair@lynosautobody.com', primary_phone: '9052771456', secondary_phone: '', fax: '', contact_name: 'Joe MacDonald')
Company.create(company_type: 'mechanic', name: 'Lyons Auto Body', street: '1020 Burnhamthorpe Road West', unit: '4', city: 'Mississauga', province: 'Ontario', postal_code: 'L5C 2S4', email: 'repair@lyonsautobody.com', primary_phone: '9052374356', secondary_phone: '', fax: '', contact_name: 'Joshua Bell')
Company.create(company_type: 'broker', name: 'Buzz\'s Trucking', street: '1 Blue Jays Way', unit: '3', city: 'Toronto', province: 'Ontario', postal_code: 'M5V 1J4', email: 'buzz.trucking@gmail.com', primary_phone: '6304950600', secondary_phone: '', fax: '', contact_name: 'Johnatan Kendel')
Company.create(company_type: 'cartage', name: 'Deans Trucking Service Inc', street: '1292 Sherwood Mills Bl', unit: '5', city: 'Mississauga', province: 'Ontario', postal_code: 'L5V 3D6', email: 'shipping@deanstruckingservices.com', primary_phone: '9055931270', secondary_phone: '', fax: '', contact_name: 'Dean Douhglass')

#Drivers
Driver.create(name: 'Ameir Hussan', street: '2372 Eglinton Ave W', unit: '', city: 'Mississuaga', postal_code: 'M9B 2B2', home_phone: '4169907505', cell_phone: '4168638475', drivers_license_number: 'H07640380731002', date_of_birth: '1950-07-18', business_name: '1', comments: 'Perfect Driving Record.  Retiring on September 30th 2013.')
Driver.create(name: 'Arshad Majid', street: '2605 Innisfil Road', unit: '', city: 'Mississuaga', postal_code: 'M9B 3R4', home_phone: '4163272895', cell_phone: '4162600471', drivers_license_number: 'M02060610830916', date_of_birth: '1981-04-14', business_name: '2', comments: 'Accident on January 9th 2009.  The road was icy and the tires slipped over the ice and hit a sign.  There was no damage to the truck, however the sign was destroyed.  He was not charged for imparied driving since they considered it an accident.')
Driver.create(name: 'Jason	Prosyk', street: '3094 Splendour Place', unit: '', city: 'Mississuaga', postal_code: 'M9B 2G9', home_phone: '4166672666', cell_phone: '4167807559', drivers_license_number: 'P75823882710707', date_of_birth: '1970-12-04', business_name: '3', comments: '')
Driver.create(name: 'Peter	Myhal', street: '6691 Harlow Road', unit: '', city: 'Mississuaga', postal_code: 'M9B 6G1', home_phone: '4164832067', cell_phone: '4168986281', drivers_license_number: 'M96476250650307', date_of_birth: '1965-10-10', business_name: '4', comments: '')
Driver.create(name: 'Allen KCollins', street: '6878 Forest Park Drive', unit: '', city: 'Mississuaga', postal_code: 'M9C 4R9', home_phone: '4161551418', cell_phone: '4161859026', drivers_license_number: 'C62770275520110', date_of_birth: '1968-08-19', business_name: '', comments: '')
Driver.create(name: 'Richard	Blasdell', street: '3039 Hillis Court', unit: '', city: 'Mississuaga', postal_code: 'M9C 3G6', home_phone: '4167592597', cell_phone: '4164743083', drivers_license_number: 'B50936555690331', date_of_birth: '1973-10-17', business_name: '', comments: '')
Driver.create(name: 'Dale Lapps', street: '7082 Estoril Road', unit: '', city: 'Mississuaga', postal_code: 'M9C 5G5', home_phone: '4165795955', cell_phone: '4162036444', drivers_license_number: 'L05281514620416', date_of_birth: '1963-11-16', business_name: '', comments: '')
Driver.create(name: 'Daniel Walker', street: '2281 Argentia Road', unit: '', city: 'Mississuaga', postal_code: 'M9C 5F5', home_phone: '4169149332', cell_phone: '4167955474', drivers_license_number: 'W02831531620127', date_of_birth: '1963-10-23', business_name: '', comments: '')
Driver.create(name: 'Archibald	Stanley', street: '6876 Century Avenue', unit: '', city: 'Mississuaga', postal_code: 'M9C 5F9', home_phone: '4169276648', cell_phone: '6044448637', drivers_license_number: 'S81260566650531', date_of_birth: '1962-11-04', business_name: '', comments: '')
Driver.create(name: 'Georgie	Willian', street: '7250 West Credit Avenue', unit: '', city: 'Mississuaga', postal_code: 'M9C 5D3', home_phone: '4165727211', cell_phone: '4168811112', drivers_license_number: 'W43532783640929', date_of_birth: '1963-10-23', business_name: '', comments: '')
Driver.create(name: 'David	Mills', street: '2677 Meadowvale Boulevard', unit: '', city: 'Mississuaga', postal_code: 'M9C 3I9', home_phone: '4168726540', cell_phone: '4166926579', drivers_license_number: 'J65125211671030', date_of_birth: '1963-12-03', business_name: '', comments: '')
Driver.create(name: 'Mohammad Hazara', street: '40 Hereford Street', unit: '', city: 'Mississuaga', postal_code: 'M9C 5G9', home_phone: '4166553604', cell_phone: '8199002716', drivers_license_number: 'H09765601830115', date_of_birth: '1961-06-02', business_name: '', comments: '')
Driver.create(name: 'Micheal	Brown', street: '32 Howland Crescent', unit: '', city: 'Mississuaga', postal_code: 'M9C 4F5', home_phone: '4165372189', cell_phone: '4161037848', drivers_license_number: 'B76105445690626', date_of_birth: '1966-08-27', business_name: '', comments: '')
Driver.create(name: 'Aaron	Clair', street: '17 Stalbridge Avenue', unit: '', city: 'Mississuaga', postal_code: 'M9C 7H6', home_phone: '4162162776', cell_phone: '4163223375', drivers_license_number: 'C50430008740218', date_of_birth: '1969-03-14', business_name: '', comments: '')

#Users
User.create(name: 'John Doe', access: 'admin', email: 'john@gofast.com', password: '12345678', password_confirmation: '12345678', remember_me: false)
User.create(name: 'Jane Doe', access: 'user', email: 'jane@gofast.com', password: '12345678', password_confirmation: '12345678', remember_me: false)
User.create(name: 'Bob Doe', access: 'driver', email: 'bob@gofast.com', password: '12345678', password_confirmation: '12345678', remember_me: false)